# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: variantxyz/rgbds-20200806:cb4fbdfcd534e43a5f8504b405acd7b8b29f5001
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4f:8a:7b:39:92:9f:c1:33:12:ea:98:fe:a2:6d:58:0f"
      - checkout:
          path: ~/medarot_1
      - run:
          name: "Get base"
          working_directory: ~
          command: |
            git clone --quiet $BASEROM_REPO ~/medarot_baserom
            cp ~/medarot_baserom/medarot_kabuto.gb ~/medarot_1/baserom_kabuto.gb
            cp ~/medarot_baserom/medarot_kuwagata.gb ~/medarot_1/baserom_kuwagata.gb
      - run:
          name: "Build ROM"
          working_directory: ~/medarot_1
          command: make kabuto kuwagata -j

workflows:
  workflow:
    jobs:
      - build:
          name: "Build ROMs"