version: 2.1
jobs:
  build:
    parameters:
      use-latest-translations:
        type: boolean
        default: false
      game-version:
        type: string
    docker:
      - image: variantxyz/rgbds-20200404:4e96cf98759de41c118cbeb4e5d7765737b95982
    environment:
      PATCH_OUTPUT: m1<< parameters.game-version >>-<<pipeline.number>>-<<pipeline.git.revision>>
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4f:8a:7b:39:92:9f:c1:33:12:ea:98:fe:a2:6d:58:0f"
      - checkout:
          path: ~/medarot_1
      - run:
          name: "Get base"
          working_directory: ~
          command: git clone --quiet $BASEROM_REPO ~/medarot_baserom && cp ~/medarot_baserom/medarot_<< parameters.game-version >>.gb ~/medarot_1/baserom_<< parameters.game-version >>.gb
      - when:
          condition: << parameters.use-latest-translations >>
          steps:
            - run:
                name: "Download latest text"
                command: wget -q --no-check-certificate "https://docs.google.com/spreadsheets/d/$TRANSLATION_SHEET_ID/export" -O ~/sheet.xlsx
            - run:
                name: "Update Dialog"
                working_directory: ~/medarot_1
                command: python3 scripts/xlsx2csv.py ~/sheet.xlsx ./text/dialog StoryText1 StoryText2 StoryText3 Snippet1 Snippet2 Snippet3 Snippet4 Snippet5 BattleText
            - run:
                name: "Update Credits"
                working_directory: ~/medarot_1
                command: python3 scripts/xlsx2csv.py ~/sheet.xlsx ./text/credits Credits
            - run:
                name: "Update Version"
                working_directory: ~/medarot_1
                command: |
                  export DATE=`date +%Y-%m-%d`
                  export SHORT_HASH=`echo $CIRCLE_SHA1 | cut -c -7`
                  sed -i -e "s/hhhhhhh/$SHORT_HASH/g" -e "s/YYYY-MM-DD/$DATE/g" -e "s/NNNNNNNN/<<pipeline.number>>/g" text/patch/version.txt && cat text/patch/version.txt
      - run:
          name: "Build ROM"
          working_directory: ~/medarot_1
          command: make << parameters.game-version >> -j
      - run:
          name: "Generate Patch"
          command: |
            mkdir patch
            ips_util create ~/medarot_1/baserom_<<  parameters.game-version >>.gb ~/medarot_1/medarot_<<  parameters.game-version >>.gb -o patch/$PATCH_OUTPUT.ips
      - store_artifacts:
          path: patch/
          destination: patch

workflows:
  workflow:
    jobs:
      - build:
          name: "Kabuto"
          use-latest-translations: false
          game-version: "kabuto"
      - build:
          name: "Kuwagata"
          use-latest-translations: false
          game-version: "kuwagata"
      - build:
          name: "Kabuto - Latest Translations"
          use-latest-translations: true
          game-version: "kabuto"
      - build:
          name: "Kuwagata - Latest Translations"
          use-latest-translations: true
          game-version: "kuwagata"
