version: 2.1

executors:
  rom-executor:
    docker:
      - image: variantxyz/rgbds-20200806:cb4fbdfcd534e43a5f8504b405acd7b8b29f5001
    working_directory: /tmp

jobs:
  build:
    executor: rom-executor
    parameters:
      use-latest-translations:
        type: boolean
        default: false
    docker:
      - image: variantxyz/rgbds-20200806:cb4fbdfcd534e43a5f8504b405acd7b8b29f5001
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4f:8a:7b:39:92:9f:c1:33:12:ea:98:fe:a2:6d:58:0f"
      - checkout:
          path: medarot_1
      - run:
          name: "Get base"
          command: |
            git clone --quiet $BASEROM_REPO ~/medarot_baserom
            cp ~/medarot_baserom/medarot_kabuto.gb ~/medarot_1/baserom_kabuto.gb
            cp ~/medarot_baserom/medarot_kuwagata.gb ~/medarot_1/baserom_kuwagata.gb
      - when:
          condition: << parameters.use-latest-translations >>
          steps:
            - run:
                name: "Download latest text"
                command: wget -q --no-check-certificate "https://docs.google.com/spreadsheets/d/$TRANSLATION_SHEET_ID/export" -O ~/sheet.xlsx
            - run:
                name: "Update Dialog"
                working_directory: medarot_1
                command: python3 scripts/xlsx2csv.py ~/sheet.xlsx ./text/dialog StoryText1 StoryText2 StoryText3 Snippet1 Snippet2 Snippet3 Snippet4 Snippet5 BattleText
            - run:
                name: "Update Credits"
                working_directory: medarot_1
                command: python3 scripts/xlsx2csv.py ~/sheet.xlsx ./text/credits Credits
            - run:
                name: "Update Lists"
                working_directory: medarot_1
                command: python3 scripts/xlsx2list.py ~/sheet.xlsx ./text/lists HeadParts RightParts LeftParts LegParts Items Medarots Medals
            - run:
                name: "Update Pointer Lists"
                working_directory: medarot_1
                command: python3 scripts/xlsx2list.py ~/sheet.xlsx ./text/ptrlists Attacks Attributes Medarotters PartDescriptions PartTypes Skills
      - run:
          name: "Build ROM"
          working_directory: medarot_1
          command: |
            export SHORT_HASH=`echo $CIRCLE_SHA1 | cut -c -7`
            export PIPELINE_NUMBER=<< pipeline.number >>
            make kabuto kuwagata -j
      - run:
          name: "Generate Patch"
          command: |
            mkdir patch
            ips_util create medarot_1/baserom_kabuto.gb medarot_1/medarot_kabuto.gb -o patch/m1kabuto-<<pipeline.number>>-<<pipeline.git.revision>>.ips
            ips_util create medarot_1/baserom_kuwagata.gb medarot_1/medarot_kuwagata.gb -o patch/m1kuwagata-<<pipeline.number>>-<<pipeline.git.revision>>.ips
            cp medarot_1/build/patch/version.txt patch/version.txt
            sha1sum medarot_1/medarot_kabuto.gb > patch/kabuto.sha1
            sha1sum medarot_1/medarot_kuwagata.gb > patch/kuwagata.sha1
      - store_artifacts:
          path: patch/
          destination: patch
      - persist_to_workspace:
          root: patch
          paths:
            - .

  release:
    executor: rom-executor
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: patch
      - store_artifacts:
          path: patch
          destination: patch
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_TAG
            ghr -t ${GHR_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./patch/

workflows:
  workflow:
    jobs:
      - build:
          name: "Build ROMs"
          use-latest-translations: false
      - build:
          name: "Build ROMs - Latest Translations"
          use-latest-translations: true
          filters:
            tags:
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
      - release:
          name: "Release"
          requires:
            - "Build ROMs - Latest Translations"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/
